### ISSUE TITLE
What happened to this?

### ISSUE THREAD

**Issue by xeruf** [tvolk131/nip-70#2]
I do not see any NIP 70 proposal on the nips repo, and the related reference implementations and websites are gone?

**Comment by tvolk131** [comment]
I moved all of the functionality here into [`nip-55`](https://github.com/tvolk131/nip-55), specifically into the [`nip_46`](https://docs.rs/nip-55/0.7.0/nip_55/nip_46/index.html) module. I mention `nip-55` in this NIP PR:

https://github.com/nostr-protocol/nips/pull/1222#issuecomment-2096914751

The reference implementation is in the repo, so I'm not sure what you're referring to. And there was never any website.
